/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Question {
    id: bigint;
    correctOption?: bigint;
    difficulty: Difficulty;
    questionText: string;
    subjectId: bigint;
    category: Category;
    options: Array<string>;
}
export interface Subject {
    id: bigint;
    code: string;
    name: string;
    description: string;
}
export enum Category {
    MCQ = "MCQ",
    Marks2 = "Marks2",
    Marks4 = "Marks4",
    Marks6 = "Marks6",
    Marks8 = "Marks8"
}
export enum Difficulty {
    Easy = "Easy",
    Hard = "Hard",
    Medium = "Medium"
}
export interface backendInterface {
    addQuestion(subjectId: bigint, questionText: string, category: Category, difficulty: Difficulty, options: Array<string>, correctOption: bigint | null): Promise<bigint>;
    addSubject(name: string, code: string, description: string): Promise<bigint>;
    deleteQuestion(id: bigint): Promise<void>;
    deleteSubject(id: bigint): Promise<void>;
    generatePaper(subjectId: bigint, examDuration: string, totalMarks: bigint, numOfQuestionsPerCategory: Array<[Category, bigint]>): Promise<bigint>;
    getAllQuestions(): Promise<Array<Question>>;
    getAllSubjects(): Promise<Array<Subject>>;
    init(): Promise<void>;
    updateQuestion(id: bigint, subjectId: bigint, questionText: string, category: Category, difficulty: Difficulty, options: Array<string>, correctOption: bigint | null): Promise<void>;
    updateSubject(id: bigint, name: string, code: string, description: string): Promise<void>;
}
import type { Category as _Category, Difficulty as _Difficulty, Question as _Question } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addQuestion(arg0: bigint, arg1: string, arg2: Category, arg3: Difficulty, arg4: Array<string>, arg5: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuestion(arg0, arg1, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg2), to_candid_Difficulty_n3(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuestion(arg0, arg1, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg2), to_candid_Difficulty_n3(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async addSubject(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSubject(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSubject(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteQuestion(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQuestion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQuestion(arg0);
            return result;
        }
    }
    async deleteSubject(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSubject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSubject(arg0);
            return result;
        }
    }
    async generatePaper(arg0: bigint, arg1: string, arg2: bigint, arg3: Array<[Category, bigint]>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.generatePaper(arg0, arg1, arg2, to_candid_vec_n6(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generatePaper(arg0, arg1, arg2, to_candid_vec_n6(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async getAllQuestions(): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQuestions();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQuestions();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSubjects(): Promise<Array<Subject>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubjects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubjects();
            return result;
        }
    }
    async init(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.init();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.init();
            return result;
        }
    }
    async updateQuestion(arg0: bigint, arg1: bigint, arg2: string, arg3: Category, arg4: Difficulty, arg5: Array<string>, arg6: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQuestion(arg0, arg1, arg2, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg3), to_candid_Difficulty_n3(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQuestion(arg0, arg1, arg2, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg3), to_candid_Difficulty_n3(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async updateSubject(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubject(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubject(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_Category_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Difficulty_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Difficulty): Difficulty {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Question_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Question): Question {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    correctOption: [] | [bigint];
    difficulty: _Difficulty;
    questionText: string;
    subjectId: bigint;
    category: _Category;
    options: Array<string>;
}): {
    id: bigint;
    correctOption?: bigint;
    difficulty: Difficulty;
    questionText: string;
    subjectId: bigint;
    category: Category;
    options: Array<string>;
} {
    return {
        id: value.id,
        correctOption: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.correctOption)),
        difficulty: from_candid_Difficulty_n12(_uploadFile, _downloadFile, value.difficulty),
        questionText: value.questionText,
        subjectId: value.subjectId,
        category: from_candid_Category_n14(_uploadFile, _downloadFile, value.category),
        options: value.options
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Easy: null;
} | {
    Hard: null;
} | {
    Medium: null;
}): Difficulty {
    return "Easy" in value ? Difficulty.Easy : "Hard" in value ? Difficulty.Hard : "Medium" in value ? Difficulty.Medium : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    MCQ: null;
} | {
    Marks2: null;
} | {
    Marks4: null;
} | {
    Marks6: null;
} | {
    Marks8: null;
}): Category {
    return "MCQ" in value ? Category.MCQ : "Marks2" in value ? Category.Marks2 : "Marks4" in value ? Category.Marks4 : "Marks6" in value ? Category.Marks6 : "Marks8" in value ? Category.Marks8 : value;
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Question>): Array<Question> {
    return value.map((x)=>from_candid_Question_n9(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Difficulty_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): _Difficulty {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_tuple_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Category, bigint]): [_Category, bigint] {
    return [
        to_candid_Category_n1(_uploadFile, _downloadFile, value[0]),
        value[1]
    ];
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    MCQ: null;
} | {
    Marks2: null;
} | {
    Marks4: null;
} | {
    Marks6: null;
} | {
    Marks8: null;
} {
    return value == Category.MCQ ? {
        MCQ: null
    } : value == Category.Marks2 ? {
        Marks2: null
    } : value == Category.Marks4 ? {
        Marks4: null
    } : value == Category.Marks6 ? {
        Marks6: null
    } : value == Category.Marks8 ? {
        Marks8: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Difficulty): {
    Easy: null;
} | {
    Hard: null;
} | {
    Medium: null;
} {
    return value == Difficulty.Easy ? {
        Easy: null
    } : value == Difficulty.Hard ? {
        Hard: null
    } : value == Difficulty.Medium ? {
        Medium: null
    } : value;
}
function to_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Category, bigint]>): Array<[_Category, bigint]> {
    return value.map((x)=>to_candid_tuple_n7(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
