/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'MCQ' : IDL.Null,
  'Marks2' : IDL.Null,
  'Marks4' : IDL.Null,
  'Marks6' : IDL.Null,
  'Marks8' : IDL.Null,
});
export const Difficulty = IDL.Variant({
  'Easy' : IDL.Null,
  'Hard' : IDL.Null,
  'Medium' : IDL.Null,
});
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'correctOption' : IDL.Opt(IDL.Nat),
  'difficulty' : Difficulty,
  'questionText' : IDL.Text,
  'subjectId' : IDL.Nat,
  'category' : Category,
  'options' : IDL.Vec(IDL.Text),
});
export const Subject = IDL.Record({
  'id' : IDL.Nat,
  'code' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  'addQuestion' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        Category,
        Difficulty,
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Nat),
      ],
      [IDL.Nat],
      [],
    ),
  'addSubject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
  'deleteSubject' : IDL.Func([IDL.Nat], [], []),
  'generatePaper' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Vec(IDL.Tuple(Category, IDL.Nat))],
      [IDL.Nat],
      [],
    ),
  'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'init' : IDL.Func([], [], []),
  'updateQuestion' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        Category,
        Difficulty,
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Nat),
      ],
      [],
      [],
    ),
  'updateSubject' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'MCQ' : IDL.Null,
    'Marks2' : IDL.Null,
    'Marks4' : IDL.Null,
    'Marks6' : IDL.Null,
    'Marks8' : IDL.Null,
  });
  const Difficulty = IDL.Variant({
    'Easy' : IDL.Null,
    'Hard' : IDL.Null,
    'Medium' : IDL.Null,
  });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'correctOption' : IDL.Opt(IDL.Nat),
    'difficulty' : Difficulty,
    'questionText' : IDL.Text,
    'subjectId' : IDL.Nat,
    'category' : Category,
    'options' : IDL.Vec(IDL.Text),
  });
  const Subject = IDL.Record({
    'id' : IDL.Nat,
    'code' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    'addQuestion' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          Category,
          Difficulty,
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Nat),
        ],
        [IDL.Nat],
        [],
      ),
    'addSubject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
    'deleteSubject' : IDL.Func([IDL.Nat], [], []),
    'generatePaper' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Vec(IDL.Tuple(Category, IDL.Nat))],
        [IDL.Nat],
        [],
      ),
    'getAllQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'init' : IDL.Func([], [], []),
    'updateQuestion' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          Category,
          Difficulty,
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Nat),
        ],
        [],
        [],
      ),
    'updateSubject' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };