/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'MCQ' : null } |
  { 'Marks2' : null } |
  { 'Marks4' : null } |
  { 'Marks6' : null } |
  { 'Marks8' : null };
export type Difficulty = { 'Easy' : null } |
  { 'Hard' : null } |
  { 'Medium' : null };
export interface Question {
  'id' : bigint,
  'correctOption' : [] | [bigint],
  'difficulty' : Difficulty,
  'questionText' : string,
  'subjectId' : bigint,
  'category' : Category,
  'options' : Array<string>,
}
export interface Subject {
  'id' : bigint,
  'code' : string,
  'name' : string,
  'description' : string,
}
export interface _SERVICE {
  'addQuestion' : ActorMethod<
    [bigint, string, Category, Difficulty, Array<string>, [] | [bigint]],
    bigint
  >,
  'addSubject' : ActorMethod<[string, string, string], bigint>,
  'deleteQuestion' : ActorMethod<[bigint], undefined>,
  'deleteSubject' : ActorMethod<[bigint], undefined>,
  'generatePaper' : ActorMethod<
    [bigint, string, bigint, Array<[Category, bigint]>],
    bigint
  >,
  'getAllQuestions' : ActorMethod<[], Array<Question>>,
  'getAllSubjects' : ActorMethod<[], Array<Subject>>,
  'init' : ActorMethod<[], undefined>,
  'updateQuestion' : ActorMethod<
    [
      bigint,
      bigint,
      string,
      Category,
      Difficulty,
      Array<string>,
      [] | [bigint],
    ],
    undefined
  >,
  'updateSubject' : ActorMethod<[bigint, string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];